# Basic X-Voice Stage2 drop-text inference config.
# Update ckpt_file and srp_ckpt_file to real local checkpoints before running.

model = "XVoice_Base_Stage2"
model_cfg = "src/x_voice/configs/XVoice_Base_Stage2.yaml"
ckpt_file = "ckpts/stage2_model_70000.safetensors"
vocab_file = "src/x_voice/infer/examples/vocab.txt"


srp_ckpt_file = "ckpts/srp_model_28000.safetensors"
srp_model_cfg = "src/rate_pred/configs/SpeedPredict_Multilingual.yaml"

ref_audio = "infer/examples/basic/basic_ref_en.wav"
gen_text = """
[main|en]I was planning to go out for dinner, but
[main|zh]外面好像快下雨了.
[main|en]Maybe I’ll just stay home and order something.
"""
gen_file = ""

gen_lang = ""
auto_detect_lang = true
normalize_text = true

output_dir = "tests"
output_file = "infer_cli_basic_stage2.wav"
save_chunk = false
remove_silence = false

vocoder_name = "vocos"
load_vocoder_from_local = true

target_rms = 0.1
cross_fade_duration = 0.15
nfe_step = 32
cfg_strength = 2.5
layered = true
cfg_strength2 = 4.0
cfg_schedule = "square"
cfg_decay_time = 0.6
sway_sampling_coef = -1.0
speed = 1.0

denoise_ref = true
loudness_norm = true
post_processing = true
reverse = false
